apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: yasithw/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CLICKHOUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: analytics-secret
                  key: CLICKHOUSE_HOST
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: analytics-secret
                  key: CLICKHOUSE_DB
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-secret
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-secret
                  key: CLICKHOUSE_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
